### ISSUE TITLE
Ajouter des events tracking pour matomo 

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/Ecolab#100]
- [ ] faire liste des choses à tracker

- [ ] lire doc : https://matomo.org/docs/event-tracking/

- [ ] mettre les trackers
